### ISSUE TITLE
Problem debugging the plugin example

### ISSUE THREAD

**Issue by 1140464BV** [epfl-disal/ns34webots#2]
Dear All,

I'm having quite a problem understanding if the radio API is working on this example. I believe I'm not able to receive any message, or at least the callback function is not being run.

I'll attach both controller and worlds file, don't mind the comments/minor changes to the original code on the controller.

Best regards,
Bruno Vieira

[Github.zip](https://github.com/epfl-disal/ns34webots/files/1492256/Github.zip)

**Comment by gjornod** [comment]
Hello Bruno,

I will try to test your controller ASAP. In the meantime, could you please try to set the destination of the wb_radio_message_new to 255.255.255.255?

I updated the README with further usage details. We will soon add a complete example.

BR, Guillaume

**Comment by 1140464BV** [comment]
@gjornod, I already tried switching the destination of wb_radio_message_new to 255.255.255.255, but there's still no callback from the radio. Will hope to hear from you again soon.

Best regards,
Bruno Vieira

**Comment by gjornod** [comment]
@1140464BV , I am almost set up to test your controller. I have managed to run webots on your world and I got errors regarding the missing plugin omnet or the libraries depending on how I load the shared library.
Which loading option (from the README) did you choose?
Please try the following (point 2 in the README);
- Have four folders at the root of your project: `controllers`, `worlds`, `plugins`, `libraries`;
- Put your controller in `controllers` and your world in `worlds`;
- Copy the output `plugins` that you got from the compilation script (it contains radio/omnet/libomnet.so, don't mind the omnet name);
- from the root of your project, run `ln -s plugins/radio/omnet/dependencies/*.so libraries/`.

With this I managed to get rid of the initialisation errors. I am not yet able to run your code, though.
Please let me know if it solves the problem, I will then update the README to add the soft linking and the file architecture accordingly.

BR, Guillaume

**Comment by 1140464BV** [comment]
@gjornod, I was just looking around at my files, and i can't seem to find where are the output plugins... Where should I run the downloaded script? If the script just creates the needed libraries, I would request you to send me the necessary files so I wouldn't need to run the script.

Either way, I wasn't getting any compilation errors... 

Best regards,
Bruno Vieira

**Comment by gjornod** [comment]
@1140464BV, you can run the script wherever it is convenient for you. The
files are located in `plugins/radio/omnet/` and
`plugins/radio/omnet/dependencies`. In the former you will find
libomnet.so, in the latter several ns-3 so files.

You can copy the whole `plugins` folder at the root of your project. It
would be better if you get the files from the script as you might get
undefined symbols if our architectures are different.

The error I am mentioning would not occur at compilation time but rather
when you launch webots.

Best regards,
Guillaume

**Comment by 1140464BV** [comment]
@gjornod, the problem is when i'm running the script there are some error regarding the folders arquitecture... It should be, because I'm using webots on a old version (8.0.1). 
If this is really the issue, we must change the script or just copy the resulting files into the project's folder...

Never saw that kind of error launching webots. But it is possible they are happening, without compromising the software running.

Best regards,
Bruno Vieira

**Comment by gjornod** [comment]
If you pull the latest version of the repo this is corrected in the
compilation script. The lines giving the error were related to the project
within which this plugin was developed and can be safely ignored (related
to a accvscacc folder). I might have forgot to remove them in the recompile
script (which does the same without redownloading ns-3) but it is the same,
the errors they create can be ignored and the lines can be removed (and
will be).

The missing libraries for plugins generally does not prevent the
controllers to run. Thus please check the placement of these shared library
files.

Other sources of error can be incompatibility of the plugin with the latest
version of ns-3, which I will check asap, and your webots version.

Best,
Guillaume

**Comment by gjornod** [comment]
Please install mercurial and run the script. You are missing the hg
command. Then please follow the information that I provided before
regarding the placement of the plugin and the folder architecture.

You can get some output from the plugin in the terminal from where you
launched webots (from the root of your project, `/path/to/webots
worlds/yourworld.wbt`). You should see some setting at the begining such as
antenna power etc. Then output for sent and received messages.

If this does not work, please provide a zip file with the whole project
(all aforementioned folders).

Best,
Guillaume

**Comment by 1140464BV** [comment]
I'll try to follow step-by-step for now, just so we don't have any more communication problem regarding this. Already successfully ran the script, what to do now? What do I copy for the project directory(3rd point of readme)?

Best regards,
Bruno Vieira

**Comment by gjornod** [comment]
Good news that you managed to run the script!
You can copy plugins at the root of your project and run webots from the
command line on worlds/yourworld.wbt.

Best,
Guillaume

**Comment by 1140464BV** [comment]
Not sure what you meant by that... I usually run webots from the command line, but with no inputs. I then use webots fully from his GUI. For example, running the example provided, what should be my next steps?

Best regards,
Bruno Vieira

**Comment by gjornod** [comment]
As mentioned before, put your controller in a `controllers` folder, your
wbt file in a `worlds` folder. Then from the root of your project, run
webots from the command line with the path to your world as only argument.
Compile the controller if necessary.

When you run, if the plugin is properly loaded, you will see some output in
the command line.

As you provided two files in a zip with no makefile and no insights of your
files architecture it is difficult for me to help you.

Best
G.

**Comment by 1140464BV** [comment]
[Example.zip](https://github.com/epfl-disal/ns34webots/files/1517944/Example.zip)

This is currently the folder for the project, it has just the controller and world folder...
What should I do to load "properly" the plugin? Already ran the script as I told you.

Besr regards,
Bruno Vieira

**Comment by 1140464BV** [comment]
Quick question: shouldn't ns-3 be running parallel with webots for the example's communications to properly work?

**Comment by DavidMansolino** [comment]
Dear Bruno,

Your project folder seems correct, however the plugin seems to be missing.
Here are the steps I recommend to follow:
  1. Compile the project (with `./compile_plugin.sh`) it should generate a `plugins` folder.
  2. Copy this folder in your Webots project folder (at the same level than `controllers` and `worlds`).
  3. Execute the following command in the terminal in order to specify the location of the plugin dependencies: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:PATH_TO_WEBOTS_PROJECT/plugins/radio/omnet/dependencies` (of course `PATH_TO_WEBOTS_PROJECT` should be replaced by the actual path).
  4. Launch Webots from the same terminal and start the simulation (of course make sure the controller is compiled before).
  5. Can you see some outputs in the terminal from which you did start Webots?

> Quick question: shouldn't ns-3 be running parallel with webots for the example's communications to properly work?

No, Webots will launch the plugin which contains ns-3, you don't need to have any other executable in parallel.

**Comment by 1140464BV** [comment]
Dear David,
I was able to get it to run properly, still there's a license problem...
Shouldn't I be able to run it with the license I have available? It requests a "PRO" license for it.

Best regards,
Bruno Vieira

**Comment by DavidMansolino** [comment]
What kind of issue do you have with the license, can you post the warning message?

**Comment by 1140464BV** [comment]
![image](https://user-images.githubusercontent.com/33874410/33436757-d04ed316-d5dd-11e7-9f9e-cf05471c1fb3.png)
This is the error.

**Comment by DavidMansolino** [comment]
Do you have a valid (non-expired) Webots PRO for the version of Webots you are using?

**Comment by 1140464BV** [comment]
I don't know what version I've been using, I believe I already did tell you the license I was using and that it was valid to webots 8.0.5 version.

**Comment by DavidMansolino** [comment]
I just checked and your license is indeed valid up to Webots 8.0.5 (make sure not to use any version more recent with this license, even if it would be highly recommended to update your license and Webots version).
However you are using an `EDU` license and a `PRO` license is required in order to use plugins (please see https://github.com/omichel/webots-doc/blob/master/guide/webots-licenses.md#webots-licences-overview).

**Comment by 1140464BV** [comment]
Was already checking that exact same information... Unfortunately, I didn't had that information earlier.

Is there any chance we (CISTER) were able to get acess to a "testing" license on this? 
We are interested in using the plugin as well as keeping the work on your software, the problem is that the process to get the validation onto renewing the license can take a while, and we need to get this work done ASAP... That is why it would be great if we had this information earlier...

Best regards,
Bruno Vieira

**Comment by gjornod** [comment]
Since your issue is not related to the plugin, could you please close it?

If you have further problems, please open a new one.

Best
Guillaume

**Comment by 1140464BV** [comment]
Sorry, and Thank you for the help.

**Comment by DavidMansolino** [comment]
> Is there any chance we (CISTER) were able to get acess to a "testing" license on this?

Yes you can ask for a trial license of Webots PRO:
To use a free 30 days trial version of Webots PRO, you need to create a user account and activate the 30 day trial license from your administration page: https://www.cyberbotics.com/administration
