### ISSUE TITLE
Only broadcast working

### ISSUE THREAD

**Issue by 1140464BV** [epfl-disal/ns34webots#3]
Dear all,

I was getting the plugin example to work, but can only get it to work changing the destination address to braodcast(255.255.255.255)... I'm not being able to get any feedback from the "receiver" robot using his own address on the emitter side to send the message....

Best regards,
Bruno Vieira

[radio.zip](https://github.com/epfl-disal/ns34webots/files/1677324/radio.zip)

**Comment by gjornod** [comment]
Dear Bruno,

The plugin has not been designed to support lower layers unicast /
multicast. A workaround is to implement application layer unicast, i.e. by
including a recipient id in your messages and checking this id when
processing the messages at the application reception.

Best regards
Guillaume

**Comment by 1140464BV** [comment]
Dear Guillaume,

so basically, your suggestion is to send all messages through broadcast, using only his contents to filter them at reception?

Best regards,
Bruno Vieira

**Comment by gjornod** [comment]
Dear Bruno,

Yes exactly. Since there is no repetition mechanism implemented, it should have a similar efficiency.

Best regards,
Guillaume
