### ISSUE TITLE
Regarding RSSI values

### ISSUE THREAD

**Issue by 1140464BV** [epfl-disal/ns34webots#4]
Hello,

I'm creating this issue as I would need to have a correct read of the RSSI values for a designated link. Is your function wb_radio_event_get_rssi(), implemented correctly? Asking this because running an example, the returned values are slightly odd... too consistent (5.53553e-315), and from time to time (1 out of 10 links) the value changes. I wasn't able to find the source file for this funtion declaration, would need to get access to it, or a guarantee that the link state value is correct.

Best regards,
Bruno Vieira

**Comment by gjornod** [comment]
Hello Bruno,

The function is actually not implemented. It is also not mentioned in `webots_radio.h`. I guess you found it in some other header.
The plugin implementation is taking advantage of the webots interface with OMNeT++, which explains for instance the name of the compiled library.

Best regards,
Guillaume
